### ISSUE TITLE
Cross-Account Table Access Example and Testing

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/dynamodb-session-store#11]
## Motivations
- There will be scenarios where applications need to share a DynamoDB Table across accounts
- The solutions to this, and the implications of what happens when the temporary sessions expire, are non-obvious

## To-Do
- [x] Review Credential Provider docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html
- [x] Create a demo app that uses a role in another account to access a table in another account
- [x] Set the session expiration to 5-15 minutes, if possible
- [x] Use [fromTemporaryCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#fromtemporarycredentials) to create a credential provider and pass it to the DynamoDB client
- [x] Repeatedly use the get/set methods on the session store, every 1 seconds
- [x] Run under a debugger and see what happens when the temporary session expires
- [x] Document the results
- [x] Save the code as an example
