### ISSUE TITLE
Attempt to parse JSON if `sess` contains a String instead of a Map

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/dynamodb-session-store#9]
## Motivations
- The `connect-dynamodb` module serializes the `sess` to a JSON string
- For compatibility of migrations, we should attempt to parse the JSON string if `sess` is a string

## To-Do
- [x] Add unit tests that fail
- [x] Parse the string
- [x] Confirm that parsing the string and re-saving the session saves it as a Map not a JSON string

**Comment by huntharo** [comment]
Done
